/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BGP: typeof import('./src/components/BGP.vue')['default']
    BGPLatestStatus: typeof import('./src/components/uptime/BGPLatestStatus.vue')['default']
    BGPUptime: typeof import('./src/components/uptime/BGPUptime.vue')['default']
    Dark: typeof import('./src/components/Dark.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    IEpArrowRightBold: typeof import('~icons/ep/arrow-right-bold')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    LatestStatus: typeof import('./src/components/uptime/LatestStatus.vue')['default']
    LinksHistory: typeof import('./src/components/uptime/LinksHistory.vue')['default']
    Loading: typeof import('./src/components/status/Loading.vue')['default']
    OSPF: typeof import('./src/components/OSPF.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
