/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BGP: typeof import('./src/components/BGP.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    IEpArrowRightBold: typeof import('~icons/ep/arrow-right-bold')['default']
    OSPF: typeof import('./src/components/OSPF.vue')['default']
  }
}
