FROM ubuntu:latest

RUN apt-get update &&  \
    apt-get install -y ca-certificates &&  \
    rm -rf /var/lib/apt/lists/*

COPY backend/main /app/main

WORKDIR "/config"

CMD ["bash","-c","/app/main"]

EXPOSE 8787