apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.webService.type }}
  ports:
  - port: {{ .Values.webService.externalPort }}
    targetPort: 8787
    protocol: TCP
    name: graph-web
  selector:
    app: {{ .Release.Name }}